const db = require('../config/database');

class CaseHistory {
  static async findByUserIdAndPartnerId(userId, partnerId) {
    const query = `
      SELECT * FROM case_histories 
      WHERE user_id = $1 AND partner_id = $2
    `;
    const result = await db.query(query, [userId, partnerId]);
    return result.rows[0];
  }

  static async createOrUpdate(caseHistoryData, client = null) {
    const dbClient = client || db;
    
    const {
      user_id,
      partner_id,
      // Section 1: Identification Data
      identification_name,
      identification_age,
      identification_gender,
      identification_father_husband_name,
      identification_education,
      identification_occupation,
      identification_marital_status,
      identification_religion,
      identification_nationality,
      identification_mother_tongue,
      identification_residence,
      identification_family_income,
      identification_socio_economic_background,
      identification_family_type,
      identification_domicile,
      identification_address,
      identification_source_of_referral,
      identification_reason_for_referral,
      // Section 2: Informant's Data
      informant_name,
      informant_age,
      informant_sex,
      informant_education,
      informant_occupation,
      informant_marital_status,
      informant_religion,
      informant_nationality,
      informant_mother_tongue,
      informant_relation_duration,
      informant_consistency,
      informant_reliability,
      // Section 3: Patient's Report
      patient_report_reliability,
      // Section 4: Chief Complaints
      chief_complaints,
      // Section 5: Family History (partial)
      family_history_family_tree,
      family_history_psychiatric_illness,
      family_history_interaction_communication,
      family_history_interaction_leadership,
      family_history_interaction_decision_making,
      family_history_interaction_role,
      family_history_interaction_family_rituals,
      family_history_interaction_cohesiveness,
      family_history_interaction_family_burden,
      family_history_expressed_emotion_warmth,
      family_history_expressed_emotion_hostility,
      family_history_expressed_emotion_critical_comments,
      family_history_expressed_emotion_emotional_over_involvement,
      family_history_expressed_emotion_reinforcement,
      family_history_consanguinity,
      family_history_economic_social_status,
      family_history_home_atmosphere,
      family_history_sibling_rivalry,
      // Section 6: Personal History
      personal_history_birth_date,
      personal_history_birth_place,
      personal_history_mother_condition_pregnancy,
      personal_history_mother_condition_delivery,
      personal_history_mother_condition_after_delivery,
      personal_history_nature_of_delivery,
      personal_history_birth_weight,
      personal_history_feeding_method,
      personal_history_milestones_physical_development,
      personal_history_neurotic_symptoms_childhood,
      personal_history_health_childhood,
      personal_history_childhood_disorders,
      personal_history_home_atmosphere_childhood,
      // Section 7: Scholastic
      scholastic_age_standard_admission,
      scholastic_highest_grade_completed,
      scholastic_change_institution_cause,
      scholastic_academic_performance,
      scholastic_reason_discontinuation,
      scholastic_adjustment_school,
      scholastic_peer_relationships,
      scholastic_disciplinary_problems,
      scholastic_further_education,
      scholastic_extracurricular_activities,
      // Section 8: Vocation
      vocation_age_starting,
      vocation_nature_position,
      vocation_change_job_cause,
      vocation_nature_duration_present_job,
      vocation_working_past_year,
      vocation_work_record,
      vocation_adjustment_peers_authority,
      vocation_work_position_ambition,
      // Section 9: Menstrual History
      menstrual_menarche_age,
      menstrual_information_acquired_from,
      menstrual_reaction,
      menstrual_associated_discomfort,
      menstrual_regularity,
      menstrual_last_date,
      menstrual_amenorrhea,
      menstrual_menopause,
      menstrual_related_symptoms,
      // Section 10: Sexual
      sexual_source_information,
      sexual_age_acquisition,
      sexual_reaction_attitude,
      sexual_libido,
      sexual_masturbation,
      sexual_fantasy,
      sexual_heterosexual_homosexual,
      sexual_pre_marital_extra_marital,
      sexual_deviance,
      // Section 11: Marital
      marital_date_of_marriage,
      marital_type,
      marital_age_at_marriage,
      marital_partner_age_at_marriage,
      marital_spouse_education,
      marital_spouse_occupation,
      marital_adjustment,
      marital_sexual_life,
      marital_number_children_details,
      marital_extra_marital_relations,
      marital_other_details,
      // Section 12: Forensic
      forensic_history,
      // Section 13: Medical
      medical_history_nature_illness,
      medical_history_doctors_consulted,
      medical_history_medication,
      medical_history_hospitalization,
      medical_history_degree_recovery,
      medical_history_accidents_operations,
      // Section 14: Premorbid Personality
      premorbid_personality_self,
      premorbid_personality_sociability,
      premorbid_personality_responsibility,
      premorbid_personality_work_leisure,
      premorbid_personality_mood,
      premorbid_personality_character,
      premorbid_personality_attitudes_standards,
      premorbid_personality_habits,
      premorbid_personality_adjustments,
      premorbid_personality_food_sleep_pattern,
      // Section 15: Fantasy Life
      fantasy_life,
      // Section 16: Present Illness
      present_illness_evolution_symptoms,
      present_illness_mode_onset,
      present_illness_course,
      present_illness_progress,
      present_illness_sleep_change,
      present_illness_appetite_change,
      present_illness_sexual_interest_change,
      present_illness_energy_change,
      present_illness_negative_history,
      present_illness_treatment_history,
      // Section 17-23
      problem_conception,
      patient_view_responsibility,
      patient_pervasive_mood,
      impact_patient_attitude,
      role_functioning_biological,
      personal_care_negative_symptoms,
      additional_information
    } = caseHistoryData;

    // Check if case history exists
    const existing = await this.findByUserIdAndPartnerId(user_id, partner_id);
    
    if (existing) {
      // Update existing
      const updateQuery = `
        UPDATE case_histories SET
          identification_name = COALESCE($1, identification_name),
          identification_age = COALESCE($2, identification_age),
          identification_gender = COALESCE($3, identification_gender),
          identification_father_husband_name = COALESCE($4, identification_father_husband_name),
          identification_education = COALESCE($5, identification_education),
          identification_occupation = COALESCE($6, identification_occupation),
          identification_marital_status = COALESCE($7, identification_marital_status),
          identification_religion = COALESCE($8, identification_religion),
          identification_nationality = COALESCE($9, identification_nationality),
          identification_mother_tongue = COALESCE($10, identification_mother_tongue),
          identification_residence = COALESCE($11, identification_residence),
          identification_family_income = COALESCE($12, identification_family_income),
          identification_socio_economic_background = COALESCE($13, identification_socio_economic_background),
          identification_family_type = COALESCE($14, identification_family_type),
          identification_domicile = COALESCE($15, identification_domicile),
          identification_address = COALESCE($16, identification_address),
          identification_source_of_referral = COALESCE($17, identification_source_of_referral),
          identification_reason_for_referral = COALESCE($18, identification_reason_for_referral),
          informant_name = COALESCE($19, informant_name),
          informant_age = COALESCE($20, informant_age),
          informant_sex = COALESCE($21, informant_sex),
          informant_education = COALESCE($22, informant_education),
          informant_occupation = COALESCE($23, informant_occupation),
          informant_marital_status = COALESCE($24, informant_marital_status),
          informant_religion = COALESCE($25, informant_religion),
          informant_nationality = COALESCE($26, informant_nationality),
          informant_mother_tongue = COALESCE($27, informant_mother_tongue),
          informant_relation_duration = COALESCE($28, informant_relation_duration),
          informant_consistency = COALESCE($29, informant_consistency),
          informant_reliability = COALESCE($30, informant_reliability),
          patient_report_reliability = COALESCE($31, patient_report_reliability),
          chief_complaints = COALESCE($32, chief_complaints),
          family_history_family_tree = COALESCE($33, family_history_family_tree),
          family_history_psychiatric_illness = COALESCE($34, family_history_psychiatric_illness),
          family_history_interaction_communication = COALESCE($35, family_history_interaction_communication),
          family_history_interaction_leadership = COALESCE($36, family_history_interaction_leadership),
          family_history_interaction_decision_making = COALESCE($37, family_history_interaction_decision_making),
          family_history_interaction_role = COALESCE($38, family_history_interaction_role),
          family_history_interaction_family_rituals = COALESCE($39, family_history_interaction_family_rituals),
          family_history_interaction_cohesiveness = COALESCE($40, family_history_interaction_cohesiveness),
          family_history_interaction_family_burden = COALESCE($41, family_history_interaction_family_burden),
          family_history_expressed_emotion_warmth = COALESCE($42, family_history_expressed_emotion_warmth),
          family_history_expressed_emotion_hostility = COALESCE($43, family_history_expressed_emotion_hostility),
          family_history_expressed_emotion_critical_comments = COALESCE($44, family_history_expressed_emotion_critical_comments),
          family_history_expressed_emotion_emotional_over_involvement = COALESCE($45, family_history_expressed_emotion_emotional_over_involvement),
          family_history_expressed_emotion_reinforcement = COALESCE($46, family_history_expressed_emotion_reinforcement),
          family_history_consanguinity = COALESCE($47, family_history_consanguinity),
          family_history_economic_social_status = COALESCE($48, family_history_economic_social_status),
          family_history_home_atmosphere = COALESCE($49, family_history_home_atmosphere),
          family_history_sibling_rivalry = COALESCE($50, family_history_sibling_rivalry),
          personal_history_birth_date = COALESCE($51, personal_history_birth_date),
          personal_history_birth_place = COALESCE($52, personal_history_birth_place),
          personal_history_mother_condition_pregnancy = COALESCE($53, personal_history_mother_condition_pregnancy),
          personal_history_mother_condition_delivery = COALESCE($54, personal_history_mother_condition_delivery),
          personal_history_mother_condition_after_delivery = COALESCE($55, personal_history_mother_condition_after_delivery),
          personal_history_nature_of_delivery = COALESCE($56, personal_history_nature_of_delivery),
          personal_history_birth_weight = COALESCE($57, personal_history_birth_weight),
          personal_history_feeding_method = COALESCE($58, personal_history_feeding_method),
          personal_history_milestones_physical_development = COALESCE($59, personal_history_milestones_physical_development),
          personal_history_neurotic_symptoms_childhood = COALESCE($60, personal_history_neurotic_symptoms_childhood),
          personal_history_health_childhood = COALESCE($61, personal_history_health_childhood),
          personal_history_childhood_disorders = COALESCE($62, personal_history_childhood_disorders),
          personal_history_home_atmosphere_childhood = COALESCE($63, personal_history_home_atmosphere_childhood),
          scholastic_age_standard_admission = COALESCE($64, scholastic_age_standard_admission),
          scholastic_highest_grade_completed = COALESCE($65, scholastic_highest_grade_completed),
          scholastic_change_institution_cause = COALESCE($66, scholastic_change_institution_cause),
          scholastic_academic_performance = COALESCE($67, scholastic_academic_performance),
          scholastic_reason_discontinuation = COALESCE($68, scholastic_reason_discontinuation),
          scholastic_adjustment_school = COALESCE($69, scholastic_adjustment_school),
          scholastic_peer_relationships = COALESCE($70, scholastic_peer_relationships),
          scholastic_disciplinary_problems = COALESCE($71, scholastic_disciplinary_problems),
          scholastic_further_education = COALESCE($72, scholastic_further_education),
          scholastic_extracurricular_activities = COALESCE($73, scholastic_extracurricular_activities),
          vocation_age_starting = COALESCE($74, vocation_age_starting),
          vocation_nature_position = COALESCE($75, vocation_nature_position),
          vocation_change_job_cause = COALESCE($76, vocation_change_job_cause),
          vocation_nature_duration_present_job = COALESCE($77, vocation_nature_duration_present_job),
          vocation_working_past_year = COALESCE($78, vocation_working_past_year),
          vocation_work_record = COALESCE($79, vocation_work_record),
          vocation_adjustment_peers_authority = COALESCE($80, vocation_adjustment_peers_authority),
          vocation_work_position_ambition = COALESCE($81, vocation_work_position_ambition),
          menstrual_menarche_age = COALESCE($82, menstrual_menarche_age),
          menstrual_information_acquired_from = COALESCE($83, menstrual_information_acquired_from),
          menstrual_reaction = COALESCE($84, menstrual_reaction),
          menstrual_associated_discomfort = COALESCE($85, menstrual_associated_discomfort),
          menstrual_regularity = COALESCE($86, menstrual_regularity),
          menstrual_last_date = COALESCE($87, menstrual_last_date),
          menstrual_amenorrhea = COALESCE($88, menstrual_amenorrhea),
          menstrual_menopause = COALESCE($89, menstrual_menopause),
          menstrual_related_symptoms = COALESCE($90, menstrual_related_symptoms),
          sexual_source_information = COALESCE($91, sexual_source_information),
          sexual_age_acquisition = COALESCE($92, sexual_age_acquisition),
          sexual_reaction_attitude = COALESCE($93, sexual_reaction_attitude),
          sexual_libido = COALESCE($94, sexual_libido),
          sexual_masturbation = COALESCE($95, sexual_masturbation),
          sexual_fantasy = COALESCE($96, sexual_fantasy),
          sexual_heterosexual_homosexual = COALESCE($97, sexual_heterosexual_homosexual),
          sexual_pre_marital_extra_marital = COALESCE($98, sexual_pre_marital_extra_marital),
          sexual_deviance = COALESCE($99, sexual_deviance),
          marital_date_of_marriage = COALESCE($100, marital_date_of_marriage),
          marital_type = COALESCE($101, marital_type),
          marital_age_at_marriage = COALESCE($102, marital_age_at_marriage),
          marital_partner_age_at_marriage = COALESCE($103, marital_partner_age_at_marriage),
          marital_spouse_education = COALESCE($104, marital_spouse_education),
          marital_spouse_occupation = COALESCE($105, marital_spouse_occupation),
          marital_adjustment = COALESCE($106, marital_adjustment),
          marital_sexual_life = COALESCE($107, marital_sexual_life),
          marital_number_children_details = COALESCE($108, marital_number_children_details),
          marital_extra_marital_relations = COALESCE($109, marital_extra_marital_relations),
          marital_other_details = COALESCE($110, marital_other_details),
          forensic_history = COALESCE($111, forensic_history),
          medical_history_nature_illness = COALESCE($112, medical_history_nature_illness),
          medical_history_doctors_consulted = COALESCE($113, medical_history_doctors_consulted),
          medical_history_medication = COALESCE($114, medical_history_medication),
          medical_history_hospitalization = COALESCE($115, medical_history_hospitalization),
          medical_history_degree_recovery = COALESCE($116, medical_history_degree_recovery),
          medical_history_accidents_operations = COALESCE($117, medical_history_accidents_operations),
          premorbid_personality_self = COALESCE($118, premorbid_personality_self),
          premorbid_personality_sociability = COALESCE($119, premorbid_personality_sociability),
          premorbid_personality_responsibility = COALESCE($120, premorbid_personality_responsibility),
          premorbid_personality_work_leisure = COALESCE($121, premorbid_personality_work_leisure),
          premorbid_personality_mood = COALESCE($122, premorbid_personality_mood),
          premorbid_personality_character = COALESCE($123, premorbid_personality_character),
          premorbid_personality_attitudes_standards = COALESCE($124, premorbid_personality_attitudes_standards),
          premorbid_personality_habits = COALESCE($125, premorbid_personality_habits),
          premorbid_personality_adjustments = COALESCE($126, premorbid_personality_adjustments),
          premorbid_personality_food_sleep_pattern = COALESCE($127, premorbid_personality_food_sleep_pattern),
          fantasy_life = COALESCE($128, fantasy_life),
          present_illness_evolution_symptoms = COALESCE($129, present_illness_evolution_symptoms),
          present_illness_mode_onset = COALESCE($130, present_illness_mode_onset),
          present_illness_course = COALESCE($131, present_illness_course),
          present_illness_progress = COALESCE($132, present_illness_progress),
          present_illness_sleep_change = COALESCE($133, present_illness_sleep_change),
          present_illness_appetite_change = COALESCE($134, present_illness_appetite_change),
          present_illness_sexual_interest_change = COALESCE($135, present_illness_sexual_interest_change),
          present_illness_energy_change = COALESCE($136, present_illness_energy_change),
          present_illness_negative_history = COALESCE($137, present_illness_negative_history),
          present_illness_treatment_history = COALESCE($138, present_illness_treatment_history),
          problem_conception = COALESCE($139, problem_conception),
          patient_view_responsibility = COALESCE($140, patient_view_responsibility),
          patient_pervasive_mood = COALESCE($141, patient_pervasive_mood),
          impact_patient_attitude = COALESCE($142, impact_patient_attitude),
          role_functioning_biological = COALESCE($143, role_functioning_biological),
          personal_care_negative_symptoms = COALESCE($144, personal_care_negative_symptoms),
          additional_information = COALESCE($145, additional_information)
        WHERE user_id = $146 AND partner_id = $147
        RETURNING *
      `;
      
      const values = [
        identification_name, identification_age, identification_gender, identification_father_husband_name,
        identification_education, identification_occupation, identification_marital_status, identification_religion,
        identification_nationality, identification_mother_tongue, identification_residence, identification_family_income,
        identification_socio_economic_background, identification_family_type, identification_domicile, identification_address,
        identification_source_of_referral, identification_reason_for_referral, informant_name, informant_age, informant_sex,
        informant_education, informant_occupation, informant_marital_status, informant_religion, informant_nationality,
        informant_mother_tongue, informant_relation_duration, informant_consistency, informant_reliability,
        patient_report_reliability, chief_complaints, family_history_family_tree, family_history_psychiatric_illness,
        family_history_interaction_communication, family_history_interaction_leadership, family_history_interaction_decision_making,
        family_history_interaction_role, family_history_interaction_family_rituals, family_history_interaction_cohesiveness,
        family_history_interaction_family_burden, family_history_expressed_emotion_warmth, family_history_expressed_emotion_hostility,
        family_history_expressed_emotion_critical_comments, family_history_expressed_emotion_emotional_over_involvement,
        family_history_expressed_emotion_reinforcement, family_history_consanguinity,
        family_history_economic_social_status, family_history_home_atmosphere, family_history_sibling_rivalry,
        personal_history_birth_date, personal_history_birth_place, personal_history_mother_condition_pregnancy,
        personal_history_mother_condition_delivery, personal_history_mother_condition_after_delivery, personal_history_nature_of_delivery,
        personal_history_birth_weight, personal_history_feeding_method, personal_history_milestones_physical_development,
        personal_history_neurotic_symptoms_childhood, personal_history_health_childhood, personal_history_childhood_disorders,
        personal_history_home_atmosphere_childhood, scholastic_age_standard_admission, scholastic_highest_grade_completed,
        scholastic_change_institution_cause, scholastic_academic_performance, scholastic_reason_discontinuation,
        scholastic_adjustment_school, scholastic_peer_relationships, scholastic_disciplinary_problems,
        scholastic_further_education, scholastic_extracurricular_activities, vocation_age_starting, vocation_nature_position,
        vocation_change_job_cause, vocation_nature_duration_present_job, vocation_working_past_year, vocation_work_record,
        vocation_adjustment_peers_authority, vocation_work_position_ambition, menstrual_menarche_age, menstrual_information_acquired_from,
        menstrual_reaction, menstrual_associated_discomfort, menstrual_regularity, menstrual_last_date, menstrual_amenorrhea,
        menstrual_menopause, menstrual_related_symptoms, sexual_source_information, sexual_age_acquisition, sexual_reaction_attitude,
        sexual_libido, sexual_masturbation, sexual_fantasy, sexual_heterosexual_homosexual, sexual_pre_marital_extra_marital,
        sexual_deviance, marital_date_of_marriage, marital_type, marital_age_at_marriage, marital_partner_age_at_marriage,
        marital_spouse_education, marital_spouse_occupation, marital_adjustment, marital_sexual_life, marital_number_children_details,
        marital_extra_marital_relations, marital_other_details, forensic_history, medical_history_nature_illness,
        medical_history_doctors_consulted, medical_history_medication, medical_history_hospitalization, medical_history_degree_recovery,
        medical_history_accidents_operations, premorbid_personality_self, premorbid_personality_sociability, premorbid_personality_responsibility,
        premorbid_personality_work_leisure, premorbid_personality_mood, premorbid_personality_character, premorbid_personality_attitudes_standards,
        premorbid_personality_habits, premorbid_personality_adjustments, premorbid_personality_food_sleep_pattern, fantasy_life,
        present_illness_evolution_symptoms, present_illness_mode_onset, present_illness_course, present_illness_progress,
        present_illness_sleep_change, present_illness_appetite_change, present_illness_sexual_interest_change, present_illness_energy_change,
        present_illness_negative_history, present_illness_treatment_history, problem_conception, patient_view_responsibility,
        patient_pervasive_mood, impact_patient_attitude, role_functioning_biological, personal_care_negative_symptoms,
        additional_information, user_id, partner_id
      ];
      
      const result = await dbClient.query(updateQuery, values);
      return result.rows[0];
    } else {
      // Insert new
      const insertQuery = `
        INSERT INTO case_histories (
          user_id, partner_id,
          identification_name, identification_age, identification_gender, identification_father_husband_name,
          identification_education, identification_occupation, identification_marital_status, identification_religion,
          identification_nationality, identification_mother_tongue, identification_residence, identification_family_income,
          identification_socio_economic_background, identification_family_type, identification_domicile, identification_address,
          identification_source_of_referral, identification_reason_for_referral, informant_name, informant_age, informant_sex,
          informant_education, informant_occupation, informant_marital_status, informant_religion, informant_nationality,
          informant_mother_tongue, informant_relation_duration, informant_consistency, informant_reliability,
          patient_report_reliability, chief_complaints, family_history_family_tree, family_history_psychiatric_illness,
          family_history_interaction_communication, family_history_interaction_leadership, family_history_interaction_decision_making,
          family_history_interaction_role, family_history_interaction_family_rituals, family_history_interaction_cohesiveness,
          family_history_interaction_family_burden, family_history_expressed_emotion_warmth, family_history_expressed_emotion_hostility,
          family_history_expressed_emotion_critical_comments, family_history_expressed_emotion_emotional_over_involvement,
          family_history_expressed_emotion_reinforcement, family_history_consanguinity,
          family_history_economic_social_status, family_history_home_atmosphere, family_history_sibling_rivalry,
          personal_history_birth_date, personal_history_birth_place, personal_history_mother_condition_pregnancy,
          personal_history_mother_condition_delivery, personal_history_mother_condition_after_delivery, personal_history_nature_of_delivery,
          personal_history_birth_weight, personal_history_feeding_method, personal_history_milestones_physical_development,
          personal_history_neurotic_symptoms_childhood, personal_history_health_childhood, personal_history_childhood_disorders,
          personal_history_home_atmosphere_childhood, scholastic_age_standard_admission, scholastic_highest_grade_completed,
          scholastic_change_institution_cause, scholastic_academic_performance, scholastic_reason_discontinuation,
          scholastic_adjustment_school, scholastic_peer_relationships, scholastic_disciplinary_problems,
          scholastic_further_education, scholastic_extracurricular_activities, vocation_age_starting, vocation_nature_position,
          vocation_change_job_cause, vocation_nature_duration_present_job, vocation_working_past_year, vocation_work_record,
          vocation_adjustment_peers_authority, vocation_work_position_ambition, menstrual_menarche_age, menstrual_information_acquired_from,
          menstrual_reaction, menstrual_associated_discomfort, menstrual_regularity, menstrual_last_date, menstrual_amenorrhea,
          menstrual_menopause, menstrual_related_symptoms, sexual_source_information, sexual_age_acquisition, sexual_reaction_attitude,
          sexual_libido, sexual_masturbation, sexual_fantasy, sexual_heterosexual_homosexual, sexual_pre_marital_extra_marital,
          sexual_deviance, marital_date_of_marriage, marital_type, marital_age_at_marriage, marital_partner_age_at_marriage,
          marital_spouse_education, marital_spouse_occupation, marital_adjustment, marital_sexual_life, marital_number_children_details,
          marital_extra_marital_relations, marital_other_details, forensic_history, medical_history_nature_illness,
          medical_history_doctors_consulted, medical_history_medication, medical_history_hospitalization, medical_history_degree_recovery,
          medical_history_accidents_operations, premorbid_personality_self, premorbid_personality_sociability, premorbid_personality_responsibility,
          premorbid_personality_work_leisure, premorbid_personality_mood, premorbid_personality_character, premorbid_personality_attitudes_standards,
          premorbid_personality_habits, premorbid_personality_adjustments, premorbid_personality_food_sleep_pattern, fantasy_life,
          present_illness_evolution_symptoms, present_illness_mode_onset, present_illness_course, present_illness_progress,
          present_illness_sleep_change, present_illness_appetite_change, present_illness_sexual_interest_change, present_illness_energy_change,
          present_illness_negative_history, present_illness_treatment_history, problem_conception, patient_view_responsibility,
          patient_pervasive_mood, impact_patient_attitude, role_functioning_biological, personal_care_negative_symptoms,
          additional_information
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $50, $51, $52, $53, $54, $55, $56, $57, $58, $59, $60, $61, $62, $63, $64, $65, $66, $67, $68, $69, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79, $80, $81, $82, $83, $84, $85, $86, $87, $88, $89, $90, $91, $92, $93, $94, $95, $96, $97, $98, $99, $100, $101, $102, $103, $104, $105, $106, $107, $108, $109, $110, $111, $112, $113, $114, $115, $116, $117, $118, $119, $120, $121, $122, $123, $124, $125, $126, $127, $128, $129, $130, $131, $132, $133, $134, $135, $136, $137, $138, $139, $140, $141, $142, $143, $144, $145
        ) RETURNING *
      `;
      
      const values = [
        user_id, partner_id, identification_name, identification_age, identification_gender, identification_father_husband_name,
        identification_education, identification_occupation, identification_marital_status, identification_religion,
        identification_nationality, identification_mother_tongue, identification_residence, identification_family_income,
        identification_socio_economic_background, identification_family_type, identification_domicile, identification_address,
        identification_source_of_referral, identification_reason_for_referral, informant_name, informant_age, informant_sex,
        informant_education, informant_occupation, informant_marital_status, informant_religion, informant_nationality,
        informant_mother_tongue, informant_relation_duration, informant_consistency, informant_reliability,
        patient_report_reliability, chief_complaints, family_history_family_tree, family_history_psychiatric_illness,
        family_history_interaction_communication, family_history_interaction_leadership, family_history_interaction_decision_making,
        family_history_interaction_role, family_history_interaction_family_rituals, family_history_interaction_cohesiveness,
        family_history_interaction_family_burden, family_history_expressed_emotion_warmth, family_history_expressed_emotion_hostility,
        family_history_expressed_emotion_critical_comments, family_history_expressed_emotion_emotional_over_involvement,
        family_history_expressed_emotion_reinforcement, family_history_consanguinity,
        family_history_economic_social_status, family_history_home_atmosphere, family_history_sibling_rivalry,
        personal_history_birth_date, personal_history_birth_place, personal_history_mother_condition_pregnancy,
        personal_history_mother_condition_delivery, personal_history_mother_condition_after_delivery, personal_history_nature_of_delivery,
        personal_history_birth_weight, personal_history_feeding_method, personal_history_milestones_physical_development,
        personal_history_neurotic_symptoms_childhood, personal_history_health_childhood, personal_history_childhood_disorders,
        personal_history_home_atmosphere_childhood, scholastic_age_standard_admission, scholastic_highest_grade_completed,
        scholastic_change_institution_cause, scholastic_academic_performance, scholastic_reason_discontinuation,
        scholastic_adjustment_school, scholastic_peer_relationships, scholastic_disciplinary_problems,
        scholastic_further_education, scholastic_extracurricular_activities, vocation_age_starting, vocation_nature_position,
        vocation_change_job_cause, vocation_nature_duration_present_job, vocation_working_past_year, vocation_work_record,
        vocation_adjustment_peers_authority, vocation_work_position_ambition, menstrual_menarche_age, menstrual_information_acquired_from,
        menstrual_reaction, menstrual_associated_discomfort, menstrual_regularity, menstrual_last_date, menstrual_amenorrhea,
        menstrual_menopause, menstrual_related_symptoms, sexual_source_information, sexual_age_acquisition, sexual_reaction_attitude,
        sexual_libido, sexual_masturbation, sexual_fantasy, sexual_heterosexual_homosexual, sexual_pre_marital_extra_marital,
        sexual_deviance, marital_date_of_marriage, marital_type, marital_age_at_marriage, marital_partner_age_at_marriage,
        marital_spouse_education, marital_spouse_occupation, marital_adjustment, marital_sexual_life, marital_number_children_details,
        marital_extra_marital_relations, marital_other_details, forensic_history, medical_history_nature_illness,
        medical_history_doctors_consulted, medical_history_medication, medical_history_hospitalization, medical_history_degree_recovery,
        medical_history_accidents_operations, premorbid_personality_self, premorbid_personality_sociability, premorbid_personality_responsibility,
        premorbid_personality_work_leisure, premorbid_personality_mood, premorbid_personality_character, premorbid_personality_attitudes_standards,
        premorbid_personality_habits, premorbid_personality_adjustments, premorbid_personality_food_sleep_pattern, fantasy_life,
        present_illness_evolution_symptoms, present_illness_mode_onset, present_illness_course, present_illness_progress,
        present_illness_sleep_change, present_illness_appetite_change, present_illness_sexual_interest_change, present_illness_energy_change,
        present_illness_negative_history, present_illness_treatment_history, problem_conception, patient_view_responsibility,
        patient_pervasive_mood, impact_patient_attitude, role_functioning_biological, personal_care_negative_symptoms,
        additional_information
      ];
      
      const result = await dbClient.query(insertQuery, values);
      return result.rows[0];
    }
  }
}

module.exports = CaseHistory;

