import React, { useState, useEffect } from 'react';
import { generatedReportAPI } from '../../services/api';
import { FileText, Calendar, User as UserIcon, Eye, Printer } from 'lucide-react';

const UserReportsTab = ({ userId }) => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedReport, setSelectedReport] = useState(null);
  const [showPreview, setShowPreview] = useState(false);

  useEffect(() => {
    loadReports();
  }, []);

  const loadReports = async () => {
    try {
      setLoading(true);
      const response = await generatedReportAPI.getUserSharedReports();
      setReports(response.data.reports || []);
      setError(null);
    } catch (err) {
      console.error('Failed to load reports:', err);
      setError('Failed to load reports. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleViewReport = (report) => {
    setSelectedReport(report);
    setShowPreview(true);
  };

  const handlePrintReport = (report) => {
    // Create printable content
    const printContent = `
      <html>
        <head>
          <title>${report.report_name}</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            h1 { color: #333; border-bottom: 2px solid #4F46E5; padding-bottom: 10px; }
            .info { margin: 20px 0; }
            .info-row { margin: 10px 0; }
            .label { font-weight: bold; display: inline-block; width: 120px; }
            .description { margin-top: 20px; white-space: pre-wrap; line-height: 1.6; }
            .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 12px; color: #666; }
          </style>
        </head>
        <body>
          <h1>${report.report_name}</h1>
          <div class="info">
            <div class="info-row"><span class="label">Client Name:</span> ${report.client_name}</div>
            <div class="info-row"><span class="label">Age:</span> ${report.client_age || 'N/A'}</div>
            <div class="info-row"><span class="label">Sex:</span> ${report.client_sex || 'N/A'}</div>
            <div class="info-row"><span class="label">Date:</span> ${new Date(report.report_date).toLocaleDateString()}</div>
            <div class="info-row"><span class="label">Therapist:</span> ${report.partner_name}</div>
          </div>
          <div class="description">
            <h2>Report Details</h2>
            <p>${report.description}</p>
          </div>
          <div class="footer">
            <p>Generated by ${report.partner_name} | ${new Date(report.created_at).toLocaleDateString()}</p>
          </div>
        </body>
      </html>
    `;

    const printWindow = window.open('', '_blank');
    printWindow.document.write(printContent);
    printWindow.document.close();
    printWindow.print();
  };

  const formatDate = (dateString) => {
    if (!dateString) return 'N/A';
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center py-12">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading reports...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="card text-center py-12">
        <div className="text-red-600 mb-4">
          <FileText className="h-16 w-16 mx-auto mb-4" />
          <p className="text-lg">{error}</p>
        </div>
        <button
          onClick={loadReports}
          className="btn btn-primary"
        >
          Try Again
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-xl font-semibold text-gray-900 mb-2">Your Reports</h2>
        <p className="text-gray-600">
          View and download reports shared with you by your therapist
        </p>
      </div>

      {reports.length === 0 ? (
        <div className="card text-center py-12">
          <FileText className="h-16 w-16 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-medium text-gray-900 mb-2">No Reports Yet</h3>
          <p className="text-gray-600">
            Your therapist hasn't shared any reports with you yet.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {reports.map((report) => (
            <div key={report.id} className="card hover:shadow-lg transition-shadow">
              <div className="flex flex-col h-full">
                {/* Report Icon */}
                <div className="flex items-center justify-center h-24 bg-primary-50 rounded-lg mb-4">
                  <FileText className="h-12 w-12 text-primary-600" />
                </div>

                {/* Report Info */}
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-gray-900 mb-2">
                    {report.report_name}
                  </h3>

                  <div className="space-y-2 text-sm text-gray-600">
                    <div className="flex items-center space-x-2">
                      <UserIcon className="h-4 w-4" />
                      <span>{report.partner_name}</span>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Calendar className="h-4 w-4" />
                      <span>{formatDate(report.shared_at || report.created_at)}</span>
                    </div>
                    {report.template_name && (
                      <div className="text-xs text-gray-500">
                        Template: {report.template_name}
                      </div>
                    )}
                  </div>
                </div>

                {/* Action Buttons */}
                <div className="mt-4 flex items-center space-x-2">
                  <button
                    onClick={() => handleViewReport(report)}
                    className="flex-1 btn btn-primary flex items-center justify-center space-x-2 text-sm"
                  >
                    <Eye className="h-4 w-4" />
                    <span>View</span>
                  </button>
                  <button
                    onClick={() => handlePrintReport(report)}
                    className="px-3 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 transition-colors"
                    title="Print Report"
                  >
                    <Printer className="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Preview Modal */}
      {showPreview && selectedReport && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-lg shadow-xl max-w-3xl w-full max-h-[90vh] overflow-y-auto">
            <div className="sticky top-0 bg-white border-b border-gray-200 p-6 flex items-center justify-between">
              <h2 className="text-xl font-bold text-gray-900">Report Details</h2>
              <button
                onClick={() => {
                  setShowPreview(false);
                  setSelectedReport(null);
                }}
                className="text-gray-400 hover:text-gray-600"
              >
                ×
              </button>
            </div>

            <div className="p-6">
              <div className="border-2 border-gray-200 rounded-lg p-6 mb-6">
                <h3 className="text-2xl font-bold text-gray-900 mb-4">
                  {selectedReport.report_name}
                </h3>

                <div className="grid grid-cols-2 gap-4 mb-6 bg-gray-50 p-4 rounded-lg">
                  <div>
                    <span className="font-medium text-gray-700">Client Name:</span>
                    <p className="text-gray-900">{selectedReport.client_name}</p>
                  </div>
                  <div>
                    <span className="font-medium text-gray-700">Age:</span>
                    <p className="text-gray-900">{selectedReport.client_age || 'N/A'}</p>
                  </div>
                  <div>
                    <span className="font-medium text-gray-700">Sex:</span>
                    <p className="text-gray-900">{selectedReport.client_sex || 'N/A'}</p>
                  </div>
                  <div>
                    <span className="font-medium text-gray-700">Date:</span>
                    <p className="text-gray-900">
                      {new Date(selectedReport.report_date).toLocaleDateString()}
                    </p>
                  </div>
                  <div className="col-span-2">
                    <span className="font-medium text-gray-700">Therapist:</span>
                    <p className="text-gray-900">{selectedReport.partner_name}</p>
                  </div>
                </div>

                <div>
                  <h4 className="font-medium text-gray-700 mb-3 text-lg">Report Details:</h4>
                  <div className="text-gray-900 whitespace-pre-wrap bg-white p-4 rounded-lg border border-gray-200 leading-relaxed">
                    {selectedReport.description}
                  </div>
                </div>

                <div className="mt-6 pt-4 border-t border-gray-200 text-sm text-gray-500">
                  <p>Generated on {formatDate(selectedReport.created_at)}</p>
                  {selectedReport.shared_at && (
                    <p>Shared on {formatDate(selectedReport.shared_at)}</p>
                  )}
                </div>
              </div>

              <div className="flex items-center justify-end">
                <button
                  onClick={() => handlePrintReport(selectedReport)}
                  className="btn btn-primary flex items-center space-x-2"
                >
                  <Printer className="h-5 w-5" />
                  <span>Print Report</span>
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default UserReportsTab;
